CREATE TABLE T_TIMELINE_POST (
    timeline_post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    post_type VARCHAR(40) NOT NULL,
    actor_type VARCHAR(20) NOT NULL,
    actor_player_id BIGINT,
    actor_name TEXT NOT NULL,
    message TEXT NOT NULL,
    coordinate VARCHAR(80),
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT,
    source_hash VARCHAR(100) NOT NULL UNIQUE,
    priority INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_t_timeline_post_published
    ON T_TIMELINE_POST (published_at DESC, timeline_post_id DESC);
CREATE INDEX idx_t_timeline_post_actor_type_published
    ON T_TIMELINE_POST (actor_player_id, post_type, published_at DESC);

CREATE TABLE T_TIMELINE_POST_REACTION (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timeline_post_id BIGINT NOT NULL REFERENCES T_TIMELINE_POST(timeline_post_id),
    account_id BIGINT NOT NULL REFERENCES M_WEB_ACCOUNT(id),
    reaction_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_t_timeline_post_reaction_account UNIQUE (timeline_post_id, account_id)
);

CREATE INDEX idx_t_timeline_post_reaction_post
    ON T_TIMELINE_POST_REACTION (timeline_post_id);

-- Keep existing social and AI history when the feed switches to the read model.
INSERT INTO T_TIMELINE_POST (
    published_at, post_type, actor_type, actor_player_id, actor_name, message, coordinate,
    source_type, source_id, source_hash, priority, created_at)
SELECT p.created_at, 'PLAYER_MESSAGE', 'PLAYER', p.player_id,
       COALESCE(mp.player_name, '不明な生存者'), p.body, NULL,
       'PLAYER_POST', p.id, 'PLAYER_POST:' || CAST(p.id AS VARCHAR), 100, p.created_at
FROM T_PLAYER_POST p
LEFT JOIN M_PLAYER mp ON mp.id = p.player_id;

INSERT INTO T_TIMELINE_POST (
    published_at, post_type, actor_type, actor_player_id, actor_name, message, coordinate,
    source_type, source_id, source_hash, priority, created_at)
SELECT c.published_at, 'WATCHPOINT', 'WATCHPOINT', c.target_player_id, 'WATCHPOINT', c.body, NULL,
       'AI_COMMENT', c.ai_comment_id, 'AI_COMMENT:' || CAST(c.ai_comment_id AS VARCHAR), 100, c.created_at
FROM T_AI_COMMENT c
WHERE c.diary_date IS NULL;

INSERT INTO T_TIMELINE_POST_REACTION (timeline_post_id, account_id, reaction_type, created_at)
SELECT tp.timeline_post_id, r.account_id,
       CASE WHEN r.reaction_type = 'HEART' THEN 'NICE' ELSE r.reaction_type END, r.created_at
FROM T_PLAYER_POST_LIKE r
JOIN T_TIMELINE_POST tp
  ON tp.source_type = 'PLAYER_POST' AND tp.source_id = r.post_id;
